### ISSUE TITLE
Unable to download assignment with rubric

### ISSUE THREAD

**Issue by tmattner** [fredrikekre/Canvas.jl#2]
Thanks for this very useful package.

I am unable to download assignments using `Canvas.assignments` if any one of the assignments contains a rubric. The error is

> ERROR: T=Union{Nothing, String}, val=Dict{String, Any}("points possible => etc
> Stacktrace:
> [1] convert′(#unused#::Type{Union{Nothing, String}}, val::Dict{String, Any})
>  @ Canvas ~/.julia/dev/Canvas/src/canvas_objects.jl:79

Changing line 603 in `autogenerated_structs.jl` to:
```
rubric_settings::Union{Dict,Nothing} # Union{String,Nothing}
```
seems to fix.

**Comment by fredrikekre** [comment]
Hi. These structs are automatically generated from the source and looks like a bug here: https://github.com/instructure/canvas-lms/blob/8b33df7f648f1579302c3ad0c7c27888542a136b/app/controllers/assignments_api_controller.rb#L582

I patched it in #3. I don't have access to a Canvas installation anymore, but let me know if there are any other problems :)

**Comment by fredrikekre** [comment]
Upstream PR: https://github.com/instructure/canvas-lms/pull/2162

**Comment by tmattner** [comment]
Excellent, thanks. That works.

Dr Trent Mattner
Engineering Mathematics Coordinator
School of Computer and Mathematical Sciences
Faculty of Sciences, Engineering and Technology
The University of Adelaide
Ph: +61 8 8313 3712

CRICOS Provider Number 00123M

IMPORTANT: This message may contain confidential or legally privileged information. If you think it was sent to you by mistake, please delete all copies and advise the sender. For the purposes ​of the SPAM Act 2003, this email is authorised by The University of Adelaide.

________________________________________
